// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
    },
    {
      path: "/admin/hosts";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts")>;
      $$route?: undefined;
    },
    {
      path: "/admin/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/admin/index")>;
    },
    {
      path: "/admin/hosts/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/new")>;
      $$route?: undefined;
    },
    {
      path: "/admin/hosts/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/admin/hosts/[id]")>;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
      children?: undefined;
    },
    {
      path: "/admin";
      id: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/admin/index")>;
          children?: undefined;
        },
        {
          path: "/hosts";
          id: "/hosts";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts")>;
          $$route?: undefined;
          children: readonly [
            {
              path: "/new";
              id: "/new";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/new")>;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/:id";
              id: "/:id";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/[id]")>;
              $$route: FileRouteEagerRef<typeof import("./src/routes/admin/hosts/[id]")>;
              children?: undefined;
            }
          ];
        }
      ];
    },
    {
      path: "/login";
      id: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
