// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
    },
    {
      path: "/admin/access-lists";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/access-lists")>;
      $$route?: undefined;
    },
    {
      path: "/admin/api-keys";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/api-keys")>;
      $$route?: undefined;
    },
    {
      path: "/admin/audit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/audit")>;
      $$route?: undefined;
    },
    {
      path: "/admin/backup";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/backup")>;
      $$route?: undefined;
    },
    {
      path: "/admin/certificates";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/certificates")>;
      $$route?: undefined;
    },
    {
      path: "/admin/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/admin/index")>;
    },
    {
      path: "/admin/redirects";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/redirects")>;
      $$route?: undefined;
    },
    {
      path: "/admin/settings";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings")>;
      $$route?: undefined;
    },
    {
      path: "/admin/streams";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/streams")>;
      $$route?: undefined;
    },
    {
      path: "/admin/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/users")>;
      $$route?: undefined;
    },
    {
      path: "/admin/hosts/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/hosts/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/new")>;
      $$route?: undefined;
    },
    {
      path: "/admin/hosts/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/admin/hosts/[id]")>;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
      children?: undefined;
    },
    {
      path: "/admin";
      id: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/admin/index")>;
          children?: undefined;
        },
        {
          path: "/audit";
          id: "/audit";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/audit")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/users";
          id: "/users";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/users")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/backup";
          id: "/backup";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/backup")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/hosts/";
          id: "/hosts/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/streams";
          id: "/streams";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/streams")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/api-keys";
          id: "/api-keys";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/api-keys")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/settings";
          id: "/settings";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/redirects";
          id: "/redirects";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/redirects")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/hosts/new";
          id: "/hosts/new";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/new")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/hosts/:id";
          id: "/hosts/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/hosts/[id]")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/admin/hosts/[id]")>;
          children?: undefined;
        },
        {
          path: "/access-lists";
          id: "/access-lists";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/access-lists")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/certificates";
          id: "/certificates";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/certificates")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/login";
      id: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
